-- MySQL Script generated by MySQL Workbench
-- Mon Jan 12 13:13:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `contacto_telefonico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_moeda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_moeda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iso` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projetos` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `id_empresa` INT NOT NULL,
  `id_tipo_moeda` INT NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_projetos_1_idx` (`id_empresa` ASC) VISIBLE,
  INDEX `fk_projetos_2_idx` (`id_tipo_moeda` ASC) VISIBLE,
  CONSTRAINT `fk_projetos_1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `mydb`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_2`
    FOREIGN KEY (`id_tipo_moeda`)
    REFERENCES `mydb`.`tipo_moeda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especializacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especializacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consultores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consultores` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `id_especializacao` INT NOT NULL,
  `id_tipo_documento` INT NOT NULL,
  `id_tipo_moeda` INT NOT NULL,
  `numero_documento_identificacao` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `valor_hora` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_consultores_1_idx` (`id_tipo_documento` ASC) VISIBLE,
  INDEX `fk_consultores_2_idx` (`id_especializacao` ASC) VISIBLE,
  UNIQUE INDEX `numero_documento_identificacao_UNIQUE` (`numero_documento_identificacao` ASC) VISIBLE,
  INDEX `fk_consultores_3_idx` (`id_tipo_moeda` ASC) VISIBLE,
  CONSTRAINT `fk_consultores_1`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `mydb`.`tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultores_2`
    FOREIGN KEY (`id_especializacao`)
    REFERENCES `mydb`.`especializacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultores_3`
    FOREIGN KEY (`id_tipo_moeda`)
    REFERENCES `mydb`.`tipo_moeda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_funcao` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participacoes` (
  `id` INT NOT NULL,
  `id_consultor` INT NOT NULL,
  `id_tipo_funcao` INT NOT NULL,
  `numero_projeto` INT NOT NULL,
  `data_inicio_participacao` DATETIME NOT NULL,
  `data_fim_participacao` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paticipacoes_1_idx` (`id_tipo_funcao` ASC) VISIBLE,
  INDEX `fk_participacoes_2_idx` (`id_consultor` ASC) VISIBLE,
  INDEX `fk_participacoes_3_idx` (`numero_projeto` ASC) VISIBLE,
  CONSTRAINT `fk_paticipacoes_1`
    FOREIGN KEY (`id_tipo_funcao`)
    REFERENCES `mydb`.`tipo_funcao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participacoes_2`
    FOREIGN KEY (`id_consultor`)
    REFERENCES `mydb`.`consultores` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participacoes_3`
    FOREIGN KEY (`numero_projeto`)
    REFERENCES `mydb`.`projetos` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
